2024-05-20 14:10:28,046 INFO    StreamThr :50596 [internal.py:wandb_internal():86] W&B internal server running at pid: 50596, started at: 2024-05-20 14:10:28.046927
2024-05-20 14:10:28,047 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status
2024-05-20 14:10:28,052 INFO    WriterThread:50596 [datastore.py:open_for_write():85] open: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\run-5vgrem24.wandb
2024-05-20 14:10:28,052 DEBUG   SenderThread:50596 [sender.py:send():380] send: header
2024-05-20 14:10:28,054 DEBUG   SenderThread:50596 [sender.py:send():380] send: run
2024-05-20 14:10:28,938 INFO    SenderThread:50596 [dir_watcher.py:__init__():211] watching files in: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files
2024-05-20 14:10:28,939 INFO    SenderThread:50596 [sender.py:_start_run_threads():1124] run started: 5vgrem24 with start time 1716185428.047927
2024-05-20 14:10:28,943 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: check_version
2024-05-20 14:10:28,943 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: check_version
2024-05-20 14:10:29,484 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: run_start
2024-05-20 14:10:29,520 DEBUG   HandlerThread:50596 [system_info.py:__init__():32] System info init
2024-05-20 14:10:29,520 DEBUG   HandlerThread:50596 [system_info.py:__init__():47] System info init done
2024-05-20 14:10:29,520 INFO    HandlerThread:50596 [system_monitor.py:start():194] Starting system monitor
2024-05-20 14:10:29,520 INFO    SystemMonitor:50596 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-05-20 14:10:29,520 INFO    HandlerThread:50596 [system_monitor.py:probe():214] Collecting system info
2024-05-20 14:10:29,527 INFO    SystemMonitor:50596 [interfaces.py:start():190] Started cpu monitoring
2024-05-20 14:10:29,527 INFO    SystemMonitor:50596 [interfaces.py:start():190] Started disk monitoring
2024-05-20 14:10:29,528 INFO    SystemMonitor:50596 [interfaces.py:start():190] Started gpu monitoring
2024-05-20 14:10:29,539 INFO    SystemMonitor:50596 [interfaces.py:start():190] Started memory monitoring
2024-05-20 14:10:29,558 INFO    SystemMonitor:50596 [interfaces.py:start():190] Started network monitoring
2024-05-20 14:10:29,569 DEBUG   HandlerThread:50596 [system_info.py:probe():196] Probing system
2024-05-20 14:10:29,570 DEBUG   HandlerThread:50596 [gitlib.py:_init_repo():56] git repository is invalid
2024-05-20 14:10:29,570 DEBUG   HandlerThread:50596 [system_info.py:probe():244] Probing system done
2024-05-20 14:10:29,570 DEBUG   HandlerThread:50596 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.9.18', 'heartbeatAt': '2024-05-20T06:10:29.569582', 'startedAt': '2024-05-20T06:10:28.040947', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'D:\\Pycharm\\ultralytics-main\\train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'host': 'DESKTOP-VH2CUSJ', 'username': 'DELL', 'executable': 'D:\\Anaconda\\envs\\DL\\python.exe', 'cpu_count': 10, 'cpu_count_logical': 16, 'cpu_freq': {'current': 2400.0, 'min': 0.0, 'max': 2400.0}, 'cpu_freq_per_core': [{'current': 2400.0, 'min': 0.0, 'max': 2400.0}], 'disk': {'/': {'total': 244.13964462280273, 'used': 188.03407669067383}}, 'gpu': 'NVIDIA GeForce RTX 4050 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 4050 Laptop GPU', 'memory_total': 6439305216}], 'memory': {'total': 15.692092895507812}}
2024-05-20 14:10:29,570 INFO    HandlerThread:50596 [system_monitor.py:probe():224] Finished collecting system info
2024-05-20 14:10:29,570 INFO    HandlerThread:50596 [system_monitor.py:probe():227] Publishing system info
2024-05-20 14:10:29,570 DEBUG   HandlerThread:50596 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2024-05-20 14:10:29,571 DEBUG   HandlerThread:50596 [system_info.py:_save_pip():68] Saving pip packages done
2024-05-20 14:10:29,571 DEBUG   HandlerThread:50596 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2024-05-20 14:10:29,954 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\conda-environment.yaml
2024-05-20 14:10:29,955 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\requirements.txt
2024-05-20 14:10:36,014 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\conda-environment.yaml
2024-05-20 14:10:36,022 DEBUG   HandlerThread:50596 [system_info.py:_save_conda():87] Saving conda packages done
2024-05-20 14:10:36,022 INFO    HandlerThread:50596 [system_monitor.py:probe():229] Finished publishing system info
2024-05-20 14:10:36,036 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:10:36,037 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: keepalive
2024-05-20 14:10:36,037 DEBUG   SenderThread:50596 [sender.py:send():380] send: files
2024-05-20 14:10:36,038 INFO    SenderThread:50596 [sender.py:_save_file():1380] saving file wandb-metadata.json with policy now
2024-05-20 14:10:36,050 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:10:36,051 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:10:36,053 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:10:36,393 DEBUG   SenderThread:50596 [sender.py:send():380] send: telemetry
2024-05-20 14:10:37,027 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:10:37,027 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_created():271] file/dir created: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\wandb-metadata.json
2024-05-20 14:10:37,332 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:10:37,337 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:10:37,337 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:10:38,791 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:10:38,791 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:10:38,791 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:10:39,048 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:10:39,449 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:10:41,547 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:10:41,547 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:10:41,547 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:10:41,547 INFO    wandb-upload_0:50596 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda\envs\DL\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Anaconda\envs\DL\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "D:\Anaconda\envs\DL\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "D:\Anaconda\envs\DL\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "D:\Anaconda\envs\DL\lib\ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\Anaconda\envs\DL\lib\ssl.py", line 1074, in _create
    self.do_handshake()
  File "D:\Anaconda\envs\DL\lib\ssl.py", line 1343, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\DL\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2550, in upload_file
    response = self._upload_file_session.put(
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda\envs\DL\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "D:\Anaconda\envs\DL\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2581, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "D:\Anaconda\envs\DL\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2550, in upload_file
    response = self._upload_file_session.put(
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\sessions.py", line 647, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "D:\Anaconda\envs\DL\lib\site-packages\requests\adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-05-20 14:10:44,486 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:10:46,536 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:10:46,536 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:10:46,536 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:10:49,138 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:10:49,581 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:10:51,063 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:10:51,064 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:10:51,065 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:10:51,157 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:10:53,176 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:10:55,195 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:10:55,232 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:10:55,337 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:10:55,337 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:10:55,337 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:10:57,219 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:10:59,241 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:00,335 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:01,267 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\config.yaml
2024-05-20 14:11:03,280 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:05,296 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:05,744 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:06,075 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:11:06,076 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:11:06,076 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:11:07,321 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:09,351 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:10,930 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:11,369 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:13,386 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:14,174 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:11:14,174 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:11:14,174 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:11:15,416 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:15,970 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:17,425 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:19,451 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:21,073 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:11:21,074 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:11:21,074 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:21,074 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:11:21,480 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:23,503 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:25,537 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:26,262 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:27,570 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:29,571 DEBUG   SystemMonitor:50596 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-05-20 14:11:29,573 DEBUG   SenderThread:50596 [sender.py:send():380] send: stats
2024-05-20 14:11:29,601 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:31,274 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:31,683 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:33,697 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:35,720 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:36,076 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:11:36,078 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:11:36,078 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:11:36,445 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:37,762 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:38,862 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:40,896 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:41,582 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:42,921 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:44,961 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:46,597 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:46,996 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:49,023 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:50,884 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:11:50,884 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:11:50,884 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:11:51,057 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:51,083 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:11:51,099 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:11:51,099 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:11:51,689 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:53,077 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:55,106 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:56,882 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:11:57,134 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:59,171 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:11:59,584 DEBUG   SenderThread:50596 [sender.py:send():380] send: stats
2024-05-20 14:12:01,219 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:01,896 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:03,223 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:05,250 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:06,089 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:12:06,104 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:12:06,104 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:12:06,966 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:07,269 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:09,304 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:11,342 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:11,986 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:13,372 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:15,394 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:16,994 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:17,426 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:19,453 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:21,096 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:12:21,110 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:12:21,111 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:12:21,474 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:22,013 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:23,499 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:25,536 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:27,174 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:27,573 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:29,611 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:29,611 DEBUG   SenderThread:50596 [sender.py:send():380] send: stats
2024-05-20 14:12:31,655 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:32,190 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:33,679 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:35,703 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:36,103 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:12:36,118 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:12:36,118 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:12:37,201 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:37,726 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:39,750 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:41,773 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:42,266 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:43,804 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:45,838 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:47,341 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:47,873 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:49,896 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:51,114 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:12:51,129 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:12:51,130 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:12:51,931 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:52,398 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:53,958 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:55,992 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:57,496 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:12:58,024 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:12:58,346 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2557] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/666233/runs/5vgrem24/wandb-metadata.json?Expires=1716271836&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=EOkbrJQgwuhcKtB3o%2FRpvTYscOUpUPi2D4tMYNpWfbNkXQrZuNMRo8xGsbvwwf7w3TpD7dHrvfhT5DnMx2G5yzAaTxlhFq2fRJDgITCxsAYhy8sSNsYNu3xE2XJhwPtqj2KEo2BC8FwF7rvnYK8FCT8wVhOvNBKaFsLw9lng7Hn7Qt2CF47C%2FW%2FT94Y6%2B3y9RIhJbe9qmFcGyaipyIdE047vQDGxXf%2BdpPqe4rtUU424ABIkCWr%2Fq69ewkL9mXY7qQiGenD%2Bl9DnVryspg3pw384JGL%2B6GQgwR%2FsLcnBrkdZPwC2m56VNAPRSVw7S6jQtnZWVMM2%2FbdzxyR0%2FF95xg%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-05-20 14:12:58,346 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2559] upload_file request headers: {'User-Agent': 'python-requests/2.28.2', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1195'}
2024-05-20 14:12:58,346 ERROR   wandb-upload_0:50596 [internal_api.py:upload_file():2561] upload_file response body: 
2024-05-20 14:12:59,612 DEBUG   SenderThread:50596 [sender.py:send():380] send: stats
2024-05-20 14:13:00,056 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:02,115 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:02,691 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:04,140 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:06,131 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:13:06,131 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:13:06,132 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:13:06,168 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:07,805 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:08,193 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:10,219 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:12,245 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:12,955 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:14,281 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:16,304 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:18,004 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:18,327 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:20,349 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:21,137 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:13:21,151 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:13:21,152 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:13:22,386 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:23,008 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:24,419 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:26,445 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:28,160 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:28,489 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:29,495 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:29,617 DEBUG   SenderThread:50596 [sender.py:send():380] send: stats
2024-05-20 14:13:31,531 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:33,194 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:33,585 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:35,600 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:36,142 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:13:36,159 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:13:36,159 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:13:37,617 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:38,283 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:39,637 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:41,682 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:43,393 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:43,716 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:45,740 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:47,773 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:48,545 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:49,791 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:51,145 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:13:51,177 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:13:51,177 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:13:51,831 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:53,686 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:53,879 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:55,899 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:57,921 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:13:58,695 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:13:59,631 DEBUG   SenderThread:50596 [sender.py:send():380] send: stats
2024-05-20 14:13:59,955 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:01,994 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:03,806 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:14:04,059 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:06,080 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:06,156 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:14:06,187 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:14:06,187 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:14:08,105 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:08,894 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:14:10,131 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:12,148 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:14,004 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:14:14,175 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:16,192 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:18,216 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:19,008 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:14:20,245 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:21,162 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:14:21,190 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:14:21,191 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:14:22,279 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:24,077 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:14:24,302 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:26,326 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:28,348 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:29,215 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:14:29,642 DEBUG   SenderThread:50596 [sender.py:send():380] send: stats
2024-05-20 14:14:30,376 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:32,394 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:34,321 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
2024-05-20 14:14:34,417 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:36,168 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: internal_messages
2024-05-20 14:14:36,197 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: stop_status
2024-05-20 14:14:36,197 DEBUG   SenderThread:50596 [sender.py:send_request():407] send_request: stop_status
2024-05-20 14:14:36,447 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:38,466 INFO    Thread-16 :50596 [dir_watcher.py:_on_file_modified():288] file/dir modified: D:\Pycharm\ultralytics-main\wandb\run-20240520_141028-5vgrem24\files\output.log
2024-05-20 14:14:39,401 DEBUG   HandlerThread:50596 [handler.py:handle_request():146] handle_request: status_report
